//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "page")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub private_metadata: Option<Json>,
    pub public_metadata: Option<Json>,
    #[sea_orm(unique)]
    pub slug: Option<String>,
    // pub publication_date: DateTime,
    pub page_config: Option<Json>,
    pub grouping_slug: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
